### PR TITLE
Pagination sort and population support.

### PR DESCRIPTION
**Pull request by janez89**
- Added for pagination sort and population support.
- Updated read.me examples and descriptions.
- increased versions: mongoose, bcrypt
- increased plugin version: 0.9
- fixed REST test issue
- added rest pagination and population support
- added new tests for paging
- added new tests for rest

### CODE REVIEW

**Comment by medanat** [comment]
+1

**Comment by janez89** [comment]
I have created a fork named as mongoose-utilities.
https://npmjs.org/package/mongoose-utilities
The pagination and Rest plugins changed.
obfuscate plugin removed.

Ideas and suggestions are welcome.

**Comment by tblobaum** [comment]
This pull request was never merged because the pagination plugin should actually be far more simple and return an instance of cursor

**Comment by janez89** [comment]
Cursor? The cursor returned after run find method.
Yes and more complex if i need sort or population functionality.

https://github.com/tblobaum/mongoose-troop/blob/master/lib/pagination.js#L42

**Pull request closed without merging**
